name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: fjzhangzzz
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push the Docker image
      run: |
        bash generate.sh
        docker images
        docker tag toolchain:latest fjzhangzzz/toolchain:latest
        docker push fjzhangzzz/toolchain:latest
